/**
 * Editing dist/_redirects safely. Cloudflare's parser switches to "dynamic"
 * mode at the first `*` or `:placeholder` source, counts every later rule as
 * dynamic regardless of shape, and stops reading the file after 100 of them
 * (2,000 static). So static rules are inserted before the first wildcard
 * rule and wildcard rules are appended after the last one, in named blocks
 * that a re-run replaces instead of stacking.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { DIST, resolvesInDist } from './build-output.ts';

export const MAX_STATIC_RULES = 2000;
export const MAX_DYNAMIC_RULES = 100;

export const REDIRECTS_FILE = `${DIST}/_redirects`;
export const isRule = (line: string) => line.trim() !== '' && !line.startsWith('#');
export const isDynamic = (line: string) => /[*:]/.test(line.split(/\s+/)[0]!);
export const sourceOf = (line: string) => line.trim().split(/\s+/)[0]!;

export function readRedirectLines(): string[] {
  return readFileSync(REDIRECTS_FILE, 'utf8').split('\n');
}

/** Replaces (or adds) the named static and dynamic blocks of one generator. */
export function setRuleBlocks(lines: string[], name: string, rules: string[], by: string): void {
  const START = `# ${name} (generated by ${by})`;
  const END = `# End of ${name}`;
  const START_DYNAMIC = `# ${name}, wildcard rules (generated by ${by})`;
  const END_DYNAMIC = `# End of ${name}, wildcard rules`;
  for (const [start, end] of [
    [START, END],
    [START_DYNAMIC, END_DYNAMIC],
  ]) {
    const from = lines.indexOf(start!);
    const to = lines.indexOf(end!);
    if (from !== -1 && to > from) lines.splice(from, to - from + 1);
  }
  const staticRules = rules.filter(rule => !isDynamic(rule));
  const dynamicRules = rules.filter(isDynamic);
  if (staticRules.length > 0) {
    const firstDynamic = lines.findIndex(line => isRule(line) && isDynamic(line));
    lines.splice(firstDynamic === -1 ? lines.length : firstDynamic, 0, START, ...staticRules, END);
  }
  if (dynamicRules.length > 0) {
    while (lines.length > 0 && lines[lines.length - 1]!.trim() === '') lines.pop();
    lines.push(START_DYNAMIC, ...dynamicRules, END_DYNAMIC, '');
  }
}

/**
 * A `/x/*` rule does not match `/x` itself, so the bare parent of every
 * wildcard rule gets a static partner pointing at the wildcard's destination
 * without the splat — when that destination is a page in the build (SEO-10).
 */
export function barePartnerRules(lines: string[]): string[] {
  const sources = new Set(lines.filter(isRule).map(sourceOf));
  const partners: string[] = [];
  for (const line of lines.filter(isRule).filter(isDynamic)) {
    const [source, destination, status = '301'] = line.trim().split(/\s+/);
    if (!source!.endsWith('/*') || destination!.includes(':')) {
      if (!destination!.endsWith('/:splat')) continue;
    }
    const bare = source!.slice(0, -2);
    if (!bare || sources.has(bare)) continue;
    const target = destination!.replace(/\/:splat$/, '').replace(/\/$/, '');
    if (!target.startsWith('/') || !resolvesInDist(target)) continue;
    partners.push(`${bare} ${target} ${status}`);
    sources.add(bare);
  }
  return partners;
}

/** Fails on the two parser limits and on static rules after a wildcard one. */
export function checkLimits(lines: string[]): { staticCount: number; dynamicCount: number } {
  const ruleLines = lines.filter(isRule);
  const firstDynamicIndex = ruleLines.findIndex(isDynamic);
  const misplaced =
    firstDynamicIndex === -1 ? [] : ruleLines.slice(firstDynamicIndex).filter(l => !isDynamic(l));
  if (misplaced.length > 0) {
    throw new Error(
      `_redirects has ${misplaced.length} static rule(s) after the first wildcard rule; Cloudflare would count them as dynamic and drop the file past 100:\n${misplaced.slice(0, 5).join('\n')}`,
    );
  }
  const dynamicCount = ruleLines.filter(isDynamic).length;
  const staticCount = ruleLines.length - dynamicCount;
  if (dynamicCount > MAX_DYNAMIC_RULES || staticCount > MAX_STATIC_RULES) {
    throw new Error(
      `_redirects exceeds Cloudflare limits: ${staticCount}/${MAX_STATIC_RULES} static, ${dynamicCount}/${MAX_DYNAMIC_RULES} dynamic`,
    );
  }
  return { staticCount, dynamicCount };
}

export function writeRedirectLines(lines: string[]): void {
  writeFileSync(REDIRECTS_FILE, lines.join('\n'));
}
