import { mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const outputDirectory = fileURLToPath(new URL("../../dist", import.meta.url));
const outputFile = fileURLToPath(new URL("../../dist/_headers", import.meta.url));

/**
 * Cache headers for the Cloudflare Pages deployment. Content-hashed files are
 * immutable by construction, so browsers can cache them for a year instead of
 * revalidating on every navigation (the default is max-age=0,
 * must-revalidate). HTML keeps the default so deploys show up immediately.
 * /_astro covers both the main site's and the Hive site's bundled assets;
 * the pagefind search index lives under the Hive mount prefix.
 */
const contents = `# Generated by scripts/hive/generate-headers.ts. Do not edit manually.
/_astro/*
  Cache-Control: public, max-age=31536000, immutable
/graphql/hive/pagefind/index/*
  Cache-Control: public, max-age=31536000, immutable
/graphql/hive/pagefind/fragment/*
  Cache-Control: public, max-age=31536000, immutable
`;

await mkdir(outputDirectory, { recursive: true });
await writeFile(outputFile, contents);

console.log(`Generated ${outputFile}`);
