main = "./src/index.ts"
name = "website-helper-worker"
compatibility_date = "2026-08-04"

routes = [{ pattern = "utils.the-guild.dev", custom_domain = true }]

send_email = [{ name = "EMAIL_SENDER" }]
