/**
 * Adds the Inspector redirects (the legacy map ported from its next.config.js) to
 * dist/_redirects; the hive generator runs first and owns the file.
 *
 * Cloudflare's parser switches to "dynamic" mode at the first `*` or
 * `:placeholder` source, counts every later rule as dynamic regardless of
 * shape, and stops reading the file after 100 of them. So the static Inspector
 * rules are inserted before the first wildcard rule, and the Inspector wildcard
 * rules are appended after the last one.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { basePath } from '../../src/inspector/lib/base-path.ts';
import { inspectorRedirects } from '../../src/inspector/redirects.ts';
import { DIST } from '../lib/build-output.ts';

const MAX_STATIC_RULES = 2000;
const MAX_DYNAMIC_RULES = 100;
const START = '# Inspector legacy routes (generated by scripts/inspector/generate-redirects.ts)';
const END = '# End of Inspector legacy routes';
const START_DYNAMIC =
  '# Inspector legacy wildcard routes (generated by scripts/inspector/generate-redirects.ts)';
const END_DYNAMIC = '# End of Inspector legacy wildcard routes';

const isRule = (line: string) => line.trim() !== '' && !line.startsWith('#');
const isDynamic = (line: string) => /[*:]/.test(line.split(/\s+/)[0]!);

const rules = Object.entries(inspectorRedirects).map(([source, destination]) => {
  const target = destination.startsWith('/') ? `${basePath}${destination}` : destination;
  return `${basePath}${source} ${target} 301`;
});
const staticBlock = [START, ...rules.filter(rule => !isDynamic(rule)), END];
const dynamicBlock = [START_DYNAMIC, ...rules.filter(isDynamic), END_DYNAMIC];

const file = `${DIST}/_redirects`;
const lines = readFileSync(file, 'utf8').split('\n');

// Re-runs replace the previous blocks instead of stacking more copies.
for (const [start, end] of [
  [START, END],
  [START_DYNAMIC, END_DYNAMIC],
]) {
  const from = lines.indexOf(start);
  const to = lines.indexOf(end);
  if (from !== -1 && to > from) lines.splice(from, to - from + 1);
}

const firstDynamic = lines.findIndex(line => isRule(line) && isDynamic(line));
lines.splice(firstDynamic === -1 ? lines.length : firstDynamic, 0, ...staticBlock);
while (lines.length > 0 && lines[lines.length - 1]!.trim() === '') lines.pop();
lines.push(...dynamicBlock, '');

// Guard the parser's ordering rule for the whole file, whoever wrote it.
const ruleLines = lines.filter(isRule);
const firstDynamicIndex = ruleLines.findIndex(isDynamic);
const misplaced =
  firstDynamicIndex === -1 ? [] : ruleLines.slice(firstDynamicIndex).filter(l => !isDynamic(l));
if (misplaced.length > 0) {
  throw new Error(
    `_redirects has ${misplaced.length} static rule(s) after the first wildcard rule; Cloudflare would count them as dynamic and drop the file past 100:\n${misplaced.slice(0, 5).join('\n')}`,
  );
}
const dynamicCount = ruleLines.filter(isDynamic).length;
const staticCount = ruleLines.length - dynamicCount;
if (dynamicCount > MAX_DYNAMIC_RULES || staticCount > MAX_STATIC_RULES) {
  throw new Error(
    `_redirects exceeds Cloudflare limits: ${staticCount}/${MAX_STATIC_RULES} static, ${dynamicCount}/${MAX_DYNAMIC_RULES} dynamic`,
  );
}

writeFileSync(file, lines.join('\n'));
console.log(
  `Inserted ${rules.length} inspector redirects (${staticBlock.length - 2} static, ${dynamicBlock.length - 2} wildcard); ${staticCount} static, ${dynamicCount} dynamic in total`,
);
