import { mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const outputDirectory = fileURLToPath(new URL("../dist", import.meta.url));
const outputFile = fileURLToPath(new URL("../dist/_headers", import.meta.url));

/**
 * Cache headers for the Workers assets server. Content-hashed files are
 * immutable by construction, so browsers can cache them for a year instead of
 * revalidating on every navigation (the default is max-age=0,
 * must-revalidate). HTML keeps the default so deploys show up immediately.
 * Paths are matched after the the-guild.dev router strips the mount prefix.
 */
const contents = `# Generated by scripts/generate-headers.ts. Do not edit manually.
/_astro/*
  Cache-Control: public, max-age=31536000, immutable
/pagefind/index/*
  Cache-Control: public, max-age=31536000, immutable
/pagefind/fragment/*
  Cache-Control: public, max-age=31536000, immutable
`;

await mkdir(outputDirectory, { recursive: true });
await writeFile(outputFile, contents);

console.log(`Generated ${outputFile}`);
