/**
 * Adds the codegen redirects to dist/_redirects (the hive generator runs
 * first and owns the file). Sources: the legacy map ported from
 * next.config.js, the parameterized legacy routes expanded concretely from
 * the plugin registry, and the /plugins/<name> → /plugins/<category>/<name>
 * category moves.
 *
 * The block is inserted before the first wildcard rule rather than appended.
 * Cloudflare's parser switches to "dynamic" mode at the first `*` or
 * `:placeholder` source, counts every later rule as dynamic regardless of
 * shape, and stops reading the file after 100 of them — appending 219
 * static rules after the Hive wildcards silently dropped all but 89.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { basePath } from '../../src/codegen/lib/base-path.ts';
import { codegenRedirects } from '../../src/codegen/redirects.ts';
import { DIST } from '../lib/build-output.ts';

const MAX_STATIC_RULES = 2000;
const MAX_DYNAMIC_RULES = 100;
const START =
  '# GraphQL Codegen legacy routes (generated by scripts/codegen/generate-redirects.ts)';
const END = '# End of GraphQL Codegen legacy routes';

const registry = JSON.parse(
  readFileSync(
    new URL('../../src/codegen/generated/plugins-registry.json', import.meta.url),
    'utf8',
  ),
) as Record<string, { category: string }>;

const rules = new Map<string, string>();
const add = (source: string, destination: string) => {
  if (source !== destination && !rules.has(source)) rules.set(source, destination);
};

for (const [source, destination] of Object.entries(codegenRedirects)) {
  add(source, destination);
}

for (const [key, { category }] of Object.entries(registry)) {
  // Old flat plugin URLs moved into category folders.
  add(`/plugins/${key}`, `/plugins/${category}/${key}`);
  // Pre-marketplace config/plugin doc routes.
  add(`/docs/generated-config/${key}`, `/plugins/${key}`);
  add(`/docs/plugins/${key}`, `/plugins/${key}`);
  if (key.endsWith('-preset')) {
    add(`/docs/presets/${key.slice(0, -'-preset'.length)}`, `/plugins/${key}`);
  }
}

const block = [
  START,
  ...[...rules].map(([source, destination]) => {
    const target = destination.startsWith('/') ? `${basePath}${destination}` : destination;
    return `${basePath}${source} ${target} 301`;
  }),
  END,
];

const isRule = (line: string) => line.trim() !== '' && !line.startsWith('#');
const isDynamic = (line: string) => /[*:]/.test(line.split(/\s+/)[0]!);

const file = `${DIST}/_redirects`;
let lines = readFileSync(file, 'utf8').split('\n');

// Re-runs replace the previous block instead of stacking another copy.
const start = lines.indexOf(START);
const end = lines.indexOf(END);
if (start !== -1 && end > start) lines.splice(start, end - start + 1);

const firstDynamic = lines.findIndex(line => isRule(line) && isDynamic(line));
const at = firstDynamic === -1 ? lines.length : firstDynamic;
lines.splice(at, 0, ...block);

// Guard the parser's ordering rule for the whole file, whoever wrote it.
const ruleLines = lines.filter(isRule);
const firstDynamicIndex = ruleLines.findIndex(isDynamic);
const misplaced =
  firstDynamicIndex === -1 ? [] : ruleLines.slice(firstDynamicIndex).filter(l => !isDynamic(l));
if (misplaced.length > 0) {
  throw new Error(
    `_redirects has ${misplaced.length} static rule(s) after the first wildcard rule; Cloudflare would count them as dynamic and drop the file past 100:\n${misplaced.slice(0, 5).join('\n')}`,
  );
}
const dynamicCount = ruleLines.filter(isDynamic).length;
const staticCount = ruleLines.length - dynamicCount;
if (dynamicCount > MAX_DYNAMIC_RULES || staticCount > MAX_STATIC_RULES) {
  throw new Error(
    `_redirects exceeds Cloudflare limits: ${staticCount}/${MAX_STATIC_RULES} static, ${dynamicCount}/${MAX_DYNAMIC_RULES} dynamic`,
  );
}

writeFileSync(file, lines.join('\n'));
console.log(
  `Inserted ${rules.size} codegen redirects before the wildcard rules (${staticCount} static, ${dynamicCount} dynamic in total)`,
);
