/**
 * Adds every registry product's legacy redirects to dist/_redirects; the
 * hive generator runs first and owns the file.
 *
 * Cloudflare's parser switches to "dynamic" mode at the first `*` or
 * `:placeholder` source, counts every later rule as dynamic regardless of
 * shape, and stops reading the file after 100 of them. So static rules are
 * inserted before the first wildcard rule and wildcard rules are appended
 * after the last one, in one block per product.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { productBasePath } from '../../src/products/define.ts';
import { DIST } from '../lib/build-output.ts';
import { loadProducts } from './registry.ts';

const MAX_STATIC_RULES = 2000;
const MAX_DYNAMIC_RULES = 100;
const isRule = (line: string) => line.trim() !== '' && !line.startsWith('#');
const isDynamic = (line: string) => /[*:]/.test(line.split(/\s+/)[0]!);

const file = `${DIST}/_redirects`;
const lines = readFileSync(file, 'utf8').split('\n');
let total = 0;

for (const product of await loadProducts()) {
  const base = productBasePath(product);
  const START = `# ${product.name} legacy routes (generated by scripts/products/generate-redirects.ts)`;
  const END = `# End of ${product.name} legacy routes`;
  const START_DYNAMIC = `# ${product.name} legacy wildcard routes (generated by scripts/products/generate-redirects.ts)`;
  const END_DYNAMIC = `# End of ${product.name} legacy wildcard routes`;
  const rules = Object.entries(product.redirects).map(([source, destination]) => {
    const target = destination.startsWith('/') ? `${base}${destination}` : destination;
    return `${base}${source} ${target} 301`;
  });
  total += rules.length;
  const staticRules = rules.filter(rule => !isDynamic(rule));
  const dynamicRules = rules.filter(isDynamic);

  // Re-runs replace the previous blocks instead of stacking more copies.
  for (const [start, end] of [
    [START, END],
    [START_DYNAMIC, END_DYNAMIC],
  ]) {
    const from = lines.indexOf(start!);
    const to = lines.indexOf(end!);
    if (from !== -1 && to > from) lines.splice(from, to - from + 1);
  }
  if (staticRules.length > 0) {
    const firstDynamic = lines.findIndex(line => isRule(line) && isDynamic(line));
    lines.splice(firstDynamic === -1 ? lines.length : firstDynamic, 0, START, ...staticRules, END);
  }
  if (dynamicRules.length > 0) {
    while (lines.length > 0 && lines[lines.length - 1]!.trim() === '') lines.pop();
    lines.push(START_DYNAMIC, ...dynamicRules, END_DYNAMIC, '');
  }
}

// Guard the parser's ordering rule for the whole file, whoever wrote it.
const ruleLines = lines.filter(isRule);
const firstDynamicIndex = ruleLines.findIndex(isDynamic);
const misplaced =
  firstDynamicIndex === -1 ? [] : ruleLines.slice(firstDynamicIndex).filter(l => !isDynamic(l));
if (misplaced.length > 0) {
  throw new Error(
    `_redirects has ${misplaced.length} static rule(s) after the first wildcard rule; Cloudflare would count them as dynamic and drop the file past 100:\n${misplaced.slice(0, 5).join('\n')}`,
  );
}
const dynamicCount = ruleLines.filter(isDynamic).length;
const staticCount = ruleLines.length - dynamicCount;
if (dynamicCount > MAX_DYNAMIC_RULES || staticCount > MAX_STATIC_RULES) {
  throw new Error(
    `_redirects exceeds Cloudflare limits: ${staticCount}/${MAX_STATIC_RULES} static, ${dynamicCount}/${MAX_DYNAMIC_RULES} dynamic`,
  );
}
writeFileSync(file, lines.join('\n'));
console.log(
  `Inserted ${total} product redirects; ${staticCount} static, ${dynamicCount} dynamic in total`,
);
