name: Blog

on: [push]

jobs:
  build:
    name: Sync
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.ref == 'refs/heads/master'

    env:
      CI: true

    steps:
      - uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@master
        with:
          node-version: 16

      - uses: actions/cache@v2
        name: Cache node_modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: actions/cache@v2
        name: Cache Client .next
        with:
          path: ${{ github.workspace }}/packages/client/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      - name: Install
        run: yarn

      - name: Sync Blog
        run: yarn sync-blog
        env:
          DEV_TO_TOKEN: ${{ secrets.DEV_TO_TOKEN }}
