name: Blog

on: [push]

jobs:
  build:
    name: Sync
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.ref == refs/heads/master

    env:
      CI: true

    steps:
      - uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - uses: actions/cache@v3
        name: Cache node_modules
        with:
          path: '**/node_modules'
          key: ${{runner.os}}-yarn-${{hashFiles('**/yarn.lock')}}
          restore-keys: |
            ${{runner.os}}-yarn-

      - uses: actions/cache@v3
        name: Cache NextJS
        with:
          path: ${{github.workspace}}/.next/cache
          key: ${{runner.os}}-nextjs-${{hashFiles('**/package-lock.json')}}-${{hashFiles('**.[jt]s', '**.[jt]sx', '**.mdx')}}
          restore-keys: |
            ${{runner.os}}-nextjs-${{hashFiles('**/package-lock.json')}}-

      - name: Install
        run: yarn

      - name: Sync Blog
        run: yarn sync-blog
        env:
          DEV_TO_TOKEN: ${{secrets.DEV_TO_TOKEN}}
