name: website-helper

on:
  push:
    branches:
      - master

concurrency: deploy-website-helper

jobs:
  deploy-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: ./.github/actions/setup
        name: setup env

      - name: typecheck
        run: pnpm --filter website-helper-worker typecheck

      - name: publish
        uses: cloudflare/wrangler-action@953926a2e2182532811c01a25e53647d93bf07c0 # v4.1.3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: ./packages/website-helper-worker
          packageManager: pnpm
