name: lint
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  lint:
    uses: the-guild-org/shared-config/.github/workflows/lint.yml@main
    with:
      script: pnpm ci:lint
      packageManager: pnpm
      packageManagerVersion: 11.25.0
      nodeVersion: 26.8.1
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
