name: website-router
on:
  push:
    branches:
      - master

concurrency: deploy-website-router

jobs:
  deploy-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: ./.github/actions/setup
        name: setup env

      - name: typecheck and test
        run: pnpm --filter guild-website-router typecheck && pnpm --filter guild-website-router test

      - name: publish
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: ./packages/website-router
          packageManager: pnpm
